#!/usr/bin/env bash
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin"

SOCKET="$HOME/.mpv-audio.sock"

[ -S "$SOCKET" ] || exit 0

printf '{ "command": ["stop"] }\n' \
  | socat - UNIX-CONNECT:"$SOCKET" >/dev/null 2>&1
